Repository GeldZeker/Geld_Zeker, pull requests merged in 2021-05, with the labels that each got.

#30 Bug/magnifier button
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scripts/UI/CellPhone/BankAppointmentDisplay.cs
Labels: bug

#32 Feature/reward system
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen schaduw.png
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen schaduw.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen schaduw.png
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen schaduw.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen brons.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen brons.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen schaduw.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen schaduw.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren schaduw.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren schaduw.png.meta
  Assets/Art/GameSprites/StudyRoom/prijzenkast leeg.png
  Assets/Art/GameSprites/StudyRoom/prijzenkast leeg.png.meta
  Assets/Scenes/DebitCardPayGame.unity
  Assets/Scenes/InvoiceDraggingGame.unity
  Assets/Scenes/MailOrderingGame.unity
  Assets/Scenes/MailPickingGame.unity
  Assets/Scenes/StudyRoom.unity
  Assets/Scripts/MiniGames/DebitCardPayment/PinDevice.cs
  Assets/Scripts/MiniGames/InvoiceDragging/InvoiceDraggingBehaviour.cs
  Assets/Scripts/MiniGames/MailOrdening/PaperPlacer.cs
  Assets/Scripts/MiniGames/MailPicking/MailPickingGameBehaviour.cs
  Assets/Scripts/Monologue/Introduction/Interaction/GameHallButtonStoryModeMonologue.asset
  Assets/Scripts/Player/Properties/PlayerRewardProperty.cs
  Assets/Scripts/Player/Properties/PlayerRewardProperty.cs.meta
  Assets/Scripts/Player/Properties/ScriptableObjects/Reward.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Reward.asset.meta
  Assets/Scripts/Player/Resources/PlayerPropertiesAsset.asset
  Assets/Scripts/UI/StudyRoom.meta
  Assets/Scripts/UI/StudyRoom/RewardImageLoader.cs
  Assets/Scripts/UI/StudyRoom/RewardImageLoader.cs.meta
Labels: feature

#34 Bug/restore gamehall
  Assets/Scenes/HomeScreen.unity
  Assets/Scripts/Player/Properties/ScriptableObjects/Happiness.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Hunger.asset
  Assets/Scripts/UI/Progression/GameResetButton.cs
Labels: bug

#35 Done
  Assets/Art/GameSprites/PlayStore.meta
  Assets/Art/GameSprites/VolunteerWorkChoosing.meta
  Assets/Scripts/Player/Properties/PlayerVolunteerProperty.cs
  Assets/Scripts/Player/Properties/PlayerVolunteerProperty.cs.meta
  Assets/Scripts/Player/Properties/ScriptableObjects/Volunteer.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Volunteer.asset.meta
Labels: enhancement

#36 Feature/volunteer c hoose screen
  Assets/Art/GameSprites/VolunteerChoosingScene.meta
  Assets/Art/GameSprites/VolunteerChoosingScene/keuze vrijw scherm.png
  Assets/Art/GameSprites/VolunteerChoosingScene/keuze vrijw scherm.png.meta
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk koffie.png
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk koffie.png.meta
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk natuur.png
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk natuur.png.meta
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk sport.png
  Assets/Art/GameSprites/VolunteerChoosingScene/wolk sport.png.meta
  Assets/Scenes/HomeScreen.unity
  Assets/Scenes/VolunteerChoosingScene.unity
  Assets/Scenes/VolunteerChoosingScene.unity.meta
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/HuiskamerIntro.asset
  Assets/Scripts/Player/Properties/PlayerVolunteerProperty.cs
  Assets/Scripts/Player/Properties/ScriptableObjects/Gender.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Happiness.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Hunger.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Volunteer.asset
  Assets/Scripts/Player/Resources/PlayerPropertiesAsset.asset
  Assets/Scripts/UI/Volunteer.meta
  Assets/Scripts/UI/Volunteer/VolunteerCloudFuntionality.cs
  Assets/Scripts/UI/Volunteer/VolunteerCloudFuntionality.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#38 Payment for volunteer work
  Assets/ClockScript.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/IncrementTask.cs
  Assets/Scenes/VolunteerWorkProcess.unity
  Assets/Scripts/Player/Progression/Quests/VolunteerWork.asset
  Assets/Scripts/Player/Progression/Quests/VolunteerWork.asset.meta
  Assets/Scripts/Player/Progression/Tasks/VolunteerWork.asset
  Assets/Scripts/Player/Progression/Tasks/VolunteerWork.asset.meta
  Assets/Scripts/Player/Properties/PlayerVolunteerProperty.cs
  Assets/Scripts/Player/Resources/QuestAsset.asset
Labels: feature

#39 Update SkipQuests-Tasks-Button
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/CompleteAllQuestsButton.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/CompleteAllQuestsButton.cs.meta
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/IncrementTask.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/MinimalValueTask.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/Quest.cs
  Assets/Scenes/HomeScreen.unity
Labels: enhancement

#40 Feature/volunteer fine tune + Bugfixes
  Assets/Art/UISprites/ButtonIcons/VolunteerWork.png
  Assets/Art/UISprites/ButtonIcons/VolunteerWork.png.meta
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scenes/HomeScreen.unity
  Assets/Scenes/InvoiceDraggingGame.unity
  Assets/Scenes/VolunteerChoosingScene.unity
  Assets/Scripts/Monologue/Introduction/Interaction/VolunteerWorkChoosingMonologue.asset
  Assets/Scripts/Monologue/Introduction/Interaction/VolunteerWorkChoosingMonologue.asset.meta
  Assets/Scripts/Monologue/Introduction/Locations/VolunteerWorkIntroMonologue.asset
  Assets/Scripts/Monologue/Introduction/Locations/VolunteerWorkIntroMonologue.asset.meta
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/VolunteerWorkChoosingIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/VolunteerWorkChoosingIntro.asset.meta
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/VolunteerWorkNavigationIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/VolunteerWorkNavigationIntro.asset.meta
  Assets/Scripts/Player/Resources/IntroductionAsset.asset
  Assets/Scripts/SceneTransitioning/LoadSceneButton.cs
  Assets/Scripts/TimeController/ClockScript.cs
  Assets/Scripts/TimeController/ClockScript.cs.meta
  Assets/Scripts/TimeController/TimeController.cs
  Assets/Scripts/UI/CellPhone/CellPhoneDisplaySystem.cs
  Assets/Scripts/UI/MainCanvasManager.cs
  Assets/Scripts/UI/Navigation/NavigationSystem.cs
  Assets/Scripts/Utlities/HideBeforeQuest.cs
  Assets/Scripts/Utlities/HideBeforeQuest.cs.meta
Labels: bug, enhancement, feature
