Repository GeldZeker/Geld_Zeker, pull requests merged in 2021-04, with the labels that each got.

#17 Feature/intro dialogue
  Assets/Art/GameSprites/Cellphone/BankApp/Appointment/Afspraak gemaakt.png
  Assets/Scripts/Monologue/Introduction/Interaction/GameHallMailOrderIntroMonologue.asset
  Assets/Scripts/Monologue/Introduction/Interaction/GameHallMailPickingIntroMonologue.asset
  Assets/Scripts/Monologue/Introduction/Interaction/PostIntroMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Interaction/PostOrderingMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/BankIntroMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/ContactloosPinIntroMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/HuiskamerIntoMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/KitchenIntroMonologue.asset
  Assets/Scripts/Monologue/Introduction/Locations/MailPickingGameIntroMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/PostOrderingMonoloog.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/MailPickingIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/PostIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/PostOrderingIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/BankIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/ContactloosPinIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/HuiskamerIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/KassaIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/KitchenIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/MailPickingGameIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/MapOrderenIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/StudeerKamerInto.asset
  Assets/Scripts/Player/PlayerDialogue/Dialogues/Supermarket/PinCardStartDialogue.asset
  Assets/Scripts/Player/Progression/Quests/BankrekeningAanvraag.asset
  Assets/Scripts/Player/Progression/Quests/BoodschappenDoen.asset
  Assets/Scripts/Player/Progression/Quests/DigiDBekijken.asset
  Assets/Scripts/Player/Progression/Quests/FactuurBetalen.asset
  Assets/Scripts/Player/Progression/Tasks/1KeerContactloosBetalen.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankAccountGesprek.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankAfspraak.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankPostOrdering.asset
  Assets/Scripts/Player/Progression/Tasks/DigiDBekijken/1KeerToeslagenBekijken.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/DigiD.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Gender.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Happiness.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Heeft Bankrekening.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Hunger.asset
  Assets/Scripts/Player/Properties/ScriptableObjects/Mail.asset
Labels: enhancement

#19 Resized InvoiceDragging
  Assets/Scenes/InvoiceDraggingGame.unity
Labels: bug

#21 Text change
  Assets/Scripts/Player/Progression/Tasks/1KeerContactloosBetalen.asset
Labels: enhancement

#22 ResetButtons scripts to one Script
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scenes/HomeScreen.unity
  Assets/Scripts/UI/IntroductionResetButton.cs
  Assets/Scripts/UI/IntroductionResetButton.cs.meta
  Assets/Scripts/UI/Progression/GameResetButton.cs
  Assets/Scripts/UI/Progression/GameResetButton.cs.meta
  Assets/Scripts/UI/Progression/QuestResetButton.cs
  Assets/Scripts/UI/Progression/QuestResetButton.cs.meta
Labels: enhancement

#23 Bug supermarket + Supermarkt introduction
  Assets/Scenes/BreadDepartment.unity
  Assets/Scenes/DairyDepartment.unity
  Assets/Scenes/FruitDepartment.unity
  Assets/Scripts/Interaction/Supermarket/AddGroceryButton.cs
  Assets/Scripts/Interaction/Supermarket/PinDeviceButton.cs
  Assets/Scripts/Monologue/Introduction/Locations/FruitDepartmentIntroMonologue.asset
  Assets/Scripts/Monologue/Introduction/Locations/FruitDepartmentIntroMonologue.asset.meta
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/FruitDepartmentIntro.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/FruitDepartmentIntro.asset.meta
  Assets/Scripts/Player/Progression/Quests/BoodschappenDoen.asset
  Assets/Scripts/Player/Progression/Tasks/Supermarkt.meta
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerBoodschappenPakken.asset
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerBoodschappenPakken.asset.meta
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerContactloosBetalen.asset
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerContactloosBetalen.asset.meta
  Assets/Scripts/Player/Resources/IntroductionAsset.asset
  Assets/Scripts/UI/Progression/GameResetButton.cs
Labels: bug, enhancement

#25 Enhancement/improve intro
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/DoOnceTask.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/IncrementTask.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/MinimalValueTask.cs
  Assets/Dependencies/BWolf/Utilities/PlayerProgression/Quests/QuestTask.cs
  Assets/Prefabs/Player/TaskDisplay.prefab
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scenes/HomeScreen.unity
  Assets/Scenes/Kitchen.unity
  Assets/Scenes/Living Room.unity
  Assets/Scripts/Monologue/Introduction/Locations/HuiskamerIntoMonoloog.asset
  Assets/Scripts/Monologue/Introduction/Locations/KitchenIntroMonologue.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/KitchenIntro.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankAccountGesprek.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankAfspraak.asset
  Assets/Scripts/Player/Progression/Tasks/BankrekeningAanvraag/BankPostOrdering.asset
  Assets/Scripts/Player/Progression/Tasks/DigiDBekijken/1KeerToeslagenBekijken.asset
  Assets/Scripts/Player/Progression/Tasks/FactuurBetalen.asset
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerContactloosBetalen.asset
  Assets/Scripts/UI/Tasks/TaskDisplay.cs
Labels: enhancement

#26 Add happiness when completing DigiD task
  Assets/Scenes/HomeScreen.unity
  Assets/Scripts/UI/CellPhone/CellPhoneDigiDAppNavigation.cs
Labels: enhancement

#27 Close game & Return to main menu.
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scenes/HomeScreen.unity
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/FruitDepartmentIntro.asset
  Assets/Scripts/Player/Progression/Quests/BoodschappenDoen.asset
  Assets/Scripts/Player/Progression/Tasks/Supermarkt/1KeerBoodschappenPakken.asset
  Assets/Scripts/SceneTransitioning/LoadSceneButton.cs
  Assets/Scripts/UI/CloseGameButton.cs
  Assets/Scripts/UI/CloseGameButton.cs.meta
  Assets/Scripts/UI/OpenCloseScreen.cs
  Assets/Scripts/UI/OpenCloseScreen.cs.meta
Labels: enhancement

#28 Enhancement/game hall in story mode
  Assets/Prefabs/Utilities/PersistentMainCanvas.prefab
  Assets/Scenes/DebitCardPayGame.unity
  Assets/Scenes/HomeScreen.unity
  Assets/Scripts/MiniGames/DebitCardPayment/PinDevice.cs
  Assets/Scripts/Monologue/Introduction/Interaction/GameHallButtonStoryModeMonologue.asset
  Assets/Scripts/Monologue/Introduction/Interaction/GameHallButtonStoryModeMonologue.asset.meta
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/GameHallButtonSM.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Interaction/GameHallButtonSM.asset.meta
  Assets/Scripts/Player/Resources/IntroductionAsset.asset
  Assets/Scripts/SceneTransitioning/GameHallBackToScene.cs
  Assets/Scripts/SceneTransitioning/GameHallBackToScene.cs.meta
  Assets/Scripts/SceneTransitioning/LoadSceneButton.cs
  Assets/Scripts/UI/MainCanvasManager.cs
Labels: enhancement

#29 Reward shelf monologue
  Assets/Art/GameSprites/StudyRoom/Trophies.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen brons.png
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen brons.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen goud.png
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen goud.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen silver.png
  Assets/Art/GameSprites/StudyRoom/Trophies/factuur betalen silver.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen brons.png
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen brons.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen goud.png
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen goud.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen silver.png
  Assets/Art/GameSprites/StudyRoom/Trophies/pinnen silver.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen goud.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen goud.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen silver.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post ordenen silver.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren brons.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren brons.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren goud.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren goud.png.meta
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren silver.png
  Assets/Art/GameSprites/StudyRoom/Trophies/post sorteren silver.png.meta
  Assets/Art/GameSprites/StudyRoom/prijzenkast.png
  Assets/Art/GameSprites/StudyRoom/prijzenkast.png.meta
  Assets/Scenes/StudyRoom.unity
  Assets/Scripts/Monologue/Introduction/Locations/StudeerKamerIntroMonoloog.asset
  Assets/Scripts/Player/Introductions/ScriptableObjects/Locations/StudeerKamerInto.asset
Labels: enhancement
